# Generated by Django 4.0.4 on 2022-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_user_avatar_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
