# Generated by Django 4.0.4 on 2022-05-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='upded_date',
            new_name='up_date',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='upp_date',
            new_name='up_date',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='upp_date',
            new_name='up_date',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='role',
        ),
    ]
