# Generated by Django 4.0.4 on 2022-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_routes_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
