# Generated by Django 4.0.4 on 2022-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_train_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
