# Generated by Django 4.0.4 on 2022-05-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_userinfo_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='routes',
        ),
    ]
