# Generated by Django 4.0.4 on 2022-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_payment_banking_remove_payment_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicKet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('up_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_ticket', to='booking.routes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_pay',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user_ticket',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='point',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_date_book',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.CharField(choices=[('CA', 'Cash'), ('MM', 'Banking MoMo'), ('ZP', 'Zalo Pay')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='empty_seat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.IntegerField(null=True, verbose_name='number-ticket'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_booking', to='booking.ticket'),
        ),
    ]
