# Generated by Django 4.0.4 on 2022-05-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'ordering': ['starting_point']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
