# Generated by Django 4.0.4 on 2022-05-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_routes_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='route_train',
        ),
        migrations.AddField(
            model_name='train',
            name='router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains', to='booking.routes'),
        ),
    ]
